---
- name: coletando info e processando
  hosts: ansible
  gather_facts: True
  become: true
  vars_files: vars/vars.yml
  tasks:

  - name: criando arquivo de demanda
    template:
      src: templates/content.j2
      dest: /opt/content.txt

  - name: Analisando quantidade de itens
    set_fact:
      num_itens: "{{ query('lines', 'cat /opt/content.txt') |length }}"  

  - name: Validar a quantidade de items na lista
    debug:
      var: num_itens

  - name: Criando inventory baseado na lista de servidores
    add_host:
      hostname: "{{ item.split(',')[0] }}"
      groups:
        - servidores
    loop: "{{ query('lines', 'cat /opt/content.txt') | from_yaml }}"


- name: Configurando Log Source
  hosts: servidores
  become: True
  tasks:

  - name: Inserir/Atualizar rsyslog.conf
    blockinfile:
      path: /etc/rsyslog.conf
      block: |
        "{{ CONTENT_RSYSLOG }}"
        
  - name: Reload do Rsyslog
    service:
      name: rsyslog
      state: restarted
      enabled: yes

  - name: Inserir/Atualizar httpd.conf
    blockinfile:
      path: /etc/httpd/conf/httpd.conf
#      insertafter: "^<VirtualHost *"
      block: |
            "{{ HTTPD_LOG }}"
      insertbefore: "^</VirtualHost>\\s?$"


